trigger: none

parameters:
- name: SPIKE
  displayName: Spike extension to publish
  type: string
  default: helloworld

variables:
  spike: ${{ parameters.SPIKE }}

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    npm install -g @vscode/vsce
  displayName: 'Install vsce'

- task: AzureCLI@2
  displayName: 'Publish using managed identity'
  inputs:
    azureSubscription: marketplace-publish
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      cd $(Build.SourcesDirectory)/src/spike/$(spike)
      vsce publish --azure-credential
