trigger: none

parameters:
- name: SPIKE
  displayName: Spike extension to publish
  type: string
  default: helloworld

variables:
  spike: ${{ parameters.SPIKE }}

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    npm install -g @vscode/vsce ovsx
  displayName: 'Install vsce and ovsx'

- script: |
    cd $(Build.SourcesDirectory)/src/spike/$(spike)
    npm install
    vsce package --no-dependencies
  displayName: 'Package extension (.vsix)'

- script: |
    cd $(Build.SourcesDirectory)/src/spike/$(spike)
    ovsx publish *.vsix -p $(OVSX_TOKEN)
  displayName: 'Publish to Open VSX'
  env:
    OVSX_TOKEN: $(OVSX_TOKEN)
