trigger:
- development

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    npm install -g @vscode/vsce
  displayName: 'Install vsce'

- task: AzureCLI@2
  displayName: 'Publish using managed identity'
  inputs:
    azureSubscription: marketplace-publish
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      cd $(Build.SourcesDirectory)/src/spike/helloworld
      vsce publish --azure-credential
